name: balance_sheet
description: A modern Flutter application for tracking personal finances with an intuitive interface, real-time calculations, and interactive visualizations.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  auth_repo:
    path: packages/auth_repo
  bloc: ^9.0.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1
  google_fonts: ^6.3.2
  intl: ^0.20.2
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - assets/images/screenshots/
