name: auth_repo
description: Authentication repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  shared_preferences: ^2.2.2

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
